import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>Cari Mentor | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-2 mx-auto my-24 max-w-7xl sm:px-6 lg:px-8">
        <h1 className="mb-12 text-4xl font-bold">About</h1>
        <h2 className="mb-12 text-xl">our team, build this website</h2>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
          <div className="">
            <img
              className="rounded-3xl"
              src="/dew.jpg"
              alt="developer1"
            />
            <h1 className="text-xl">Hanif Dwi Prasetiyo</h1>
          </div>
          <div className="">
            <img
              className="rounded-3xl"
              src="/dew.jpg"
              alt="developer2"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default about;
