import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>Cari Mentor | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-48 my-32">
        <h1>About</h1>
        <p>
          Veniam officia consectetur aliqua exercitation consequat tempor ipsum.
          Sint aute occaecat laborum eu sint et voluptate ipsum cupidatat ipsum.
          Commodo quis fugiat laborum velit ex do. Id sint ad proident proident
          voluptate Lorem dolore. Dolor non ad adipisicing nisi id id
          adipisicing esse ipsum do cupidatat irure. Mollit occaecat incididunt
          proident nostrud nostrud laborum est minim reprehenderit aute.
        </p>
      </div>
    </>
  );
};

export default about;
