import Head from "next/head";
import HomeContent from "../app/content/HomeContent";

export default function App() {
  return (
    <div>
      <Head>
        <title>Cari Mentor | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContent />
    </div>
  );
}
